name: Read Secrets Example

# Add the workflow_dispatch event for manual triggering
#on:
#  workflow_dispatch:
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run  Inline Script
        run: |

         curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GHToken }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/selvan123/HelloWorld/hooks | jq '.type'
